# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: "崔天祥的主页"
  params:
    description: Site description in Chinese...
  menu:
    main:
  - name: "关于"
    url: '#about'
    weight: 10
  # - name: Blogs
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  - name: "谈话"
    url: '#talks'
    weight: 45
  - name: "出版物"
    url: '#publications'
    weight: 50
  - name: "技能"
    url: '#skills'
    weight: 15
  - name: "联系方式"
    url: '#contact'
    weight: 70
  - name: "关键词"
    url: '#tags'
    weight: 60
  - name: "经历"
    url: '#experience'
    weight: 20
